Repository rapidsai/shared-workflows, pull requests merged in 2025-04, with the labels that each got.

#325 Enable proxy cache on NVKS V100 nodes.
  .github/workflows/conda-cpp-tests.yaml
  .github/workflows/conda-python-tests.yaml
  .github/workflows/wheels-test.yaml
Labels: feature request, non-breaking

#318 make `RAPIDS_AUX_SECRET_1` be an input variable secret name, not the secret itself
  .github/workflows/build-in-devcontainer.yaml
  .github/workflows/wheels-test.yaml
Labels: breaking, improvement

#326 Add pipefail to devcontainer builds.
  .github/workflows/build-in-devcontainer.yaml
Labels: bug, non-breaking

#328 add mkdir -p to devcontainer setup
  .github/workflows/build-in-devcontainer.yaml
Labels: bug, non-breaking

#330 Use the variable `package-name` for Distribution name in wheel builds
  .github/workflows/wheels-build.yaml
Labels: improvement, non-breaking

#329 Add `env` and `timeout-minutes` inputs to build-in-devcontainer.yaml
  .github/workflows/build-in-devcontainer.yaml
Labels: improvement, non-breaking
