Repository rapidsai/shared-workflows, pull requests merged in 2025-05, with the labels that each got.

#333 Drop CUDA 11 builds/tests
  .github/workflows/conda-cpp-build.yaml
  .github/workflows/conda-cpp-tests.yaml
  .github/workflows/conda-python-build.yaml
  .github/workflows/conda-python-tests.yaml
  .github/workflows/wheels-build.yaml
  .github/workflows/wheels-test.yaml
Labels: feature request, non-breaking

#340 make artifact uploads optional
  .github/workflows/conda-cpp-build.yaml
  .github/workflows/conda-python-build.yaml
  .github/workflows/wheels-build.yaml
Labels: improvement, non-breaking

#343 Fix type mismatch for graphQL on single selects
  .github/workflows/project-get-set-single-select-field.yaml
Labels: bug, non-breaking

#268 Add Python 3.13
  .github/workflows/conda-cpp-tests.yaml
  .github/workflows/conda-python-build.yaml
  .github/workflows/conda-python-tests.yaml
  .github/workflows/wheels-build.yaml
  .github/workflows/wheels-test.yaml
Labels: improvement, non-breaking

#348 make input validation, upload logic in build workflows stricter
  .github/workflows/conda-cpp-build.yaml
  .github/workflows/conda-python-build.yaml
  .github/workflows/wheels-build.yaml
Labels: breaking, improvement

#349 Enable pre-commit rules.
  .github/actionlint.yaml
  .github/workflows/breaking-change-alert.yaml
  .github/workflows/build-in-devcontainer.yaml
  .github/workflows/changed-files.yaml
  .github/workflows/conda-cpp-build.yaml
  .github/workflows/conda-cpp-post-build-checks.yaml
  .github/workflows/conda-cpp-tests.yaml
  .github/workflows/conda-python-build.yaml
  .github/workflows/conda-python-tests.yaml
  .github/workflows/conda-upload-packages.yaml
  .github/workflows/custom-job.yaml
  .github/workflows/project-get-item-id.yaml
  .github/workflows/project-get-set-iteration-field.yaml
  .github/workflows/project-get-set-single-select-field.yaml
  .github/workflows/project-set-text-date-numeric-field.yaml
  .github/workflows/project-update-linked-issues.yaml
  .github/workflows/wheels-build.yaml
  .github/workflows/wheels-publish.yaml
  .github/workflows/wheels-test.yaml
  .pre-commit-config.yaml
Labels: improvement, non-breaking

#350 Replace all `-F` usage with `-f`
  .github/workflows/project-get-item-id.yaml
  .github/workflows/project-get-set-iteration-field.yaml
  .github/workflows/project-get-set-single-select-field.yaml
  .github/workflows/project-set-text-date-numeric-field.yaml
  .github/workflows/project-update-linked-issues.yaml
  .pre-commit-config.yaml
Labels: bug, non-breaking

#352 Forward-merge branch-25.06 into branch-25.08
  .github/actionlint.yaml
  .github/workflows/breaking-change-alert.yaml
  .github/workflows/build-in-devcontainer.yaml
  .github/workflows/changed-files.yaml
  .github/workflows/conda-cpp-build.yaml
  .github/workflows/conda-cpp-post-build-checks.yaml
  .github/workflows/conda-cpp-tests.yaml
  .github/workflows/conda-python-build.yaml
  .github/workflows/conda-python-tests.yaml
  .github/workflows/conda-upload-packages.yaml
  .github/workflows/custom-job.yaml
  .github/workflows/project-get-item-id.yaml
  .github/workflows/project-get-set-iteration-field.yaml
  .github/workflows/project-get-set-single-select-field.yaml
  .github/workflows/project-set-text-date-numeric-field.yaml
  .github/workflows/project-update-linked-issues.yaml
  .github/workflows/wheels-build.yaml
  .github/workflows/wheels-publish.yaml
  .github/workflows/wheels-test.yaml
  .pre-commit-config.yaml
Labels: improvement, non-breaking

#354 Revert CUDA 11 drop
  .github/workflows/conda-cpp-build.yaml
  .github/workflows/conda-cpp-tests.yaml
  .github/workflows/conda-python-build.yaml
  .github/workflows/conda-python-tests.yaml
  .github/workflows/wheels-build.yaml
  .github/workflows/wheels-test.yaml
Labels: bug, non-breaking

#357 custom-job: deprecate 'run_script' input, in favor of 'script'
  .github/workflows/conda-cpp-build.yaml
  .github/workflows/conda-cpp-tests.yaml
  .github/workflows/conda-python-build.yaml
  .github/workflows/conda-python-tests.yaml
  .github/workflows/custom-job.yaml
  .github/workflows/wheels-build.yaml
  .github/workflows/wheels-test.yaml
Labels: improvement, non-breaking

#359 fix: update jq command to remove `exit 4` errors when there is no linked issue
  .github/workflows/project-update-linked-issues.yaml
Labels: bug, non-breaking

#362 make 'script' input required
  .github/workflows/conda-cpp-build.yaml
  .github/workflows/conda-cpp-tests.yaml
  .github/workflows/conda-python-build.yaml
  .github/workflows/conda-python-tests.yaml
  .github/workflows/wheels-test.yaml
Labels: breaking, improvement

#364 Use GitHub Actions artifacts in Anaconda uploads
  .github/workflows/conda-upload-packages.yaml
  .github/workflows/wheels-publish.yaml
Labels: breaking, improvement

#331 Add 'build_workflow_name' input, to allow overriding where scripts look for artifacts
  .github/workflows/conda-cpp-tests.yaml
  .github/workflows/conda-python-tests.yaml
  .github/workflows/custom-job.yaml
  .github/workflows/wheels-test.yaml
Labels: improvement, non-breaking

#371 Drop CUDA 11
  .github/workflows/conda-cpp-build.yaml
  .github/workflows/conda-cpp-tests.yaml
  .github/workflows/conda-python-build.yaml
  .github/workflows/conda-python-tests.yaml
  .github/workflows/wheels-build.yaml
  .github/workflows/wheels-test.yaml
Labels: breaking, improvement
