Repository rapidsai/shared-workflows, pull requests merged in 2025-03, with the labels that each got.

#289 Revert "Temporarily reduce A100 testing (#285)"
  .github/workflows/conda-cpp-tests.yaml
  .github/workflows/conda-python-tests.yaml
  .github/workflows/wheels-test.yaml
Labels: improvement, non-breaking

#290 Remove `a100` conditional for proxy cache
  .github/workflows/conda-cpp-tests.yaml
  .github/workflows/conda-python-tests.yaml
  .github/workflows/wheels-test.yaml
Labels: improvement, non-breaking

#286 Use `twine` to upload wheels
  .github/workflows/wheels-publish.yaml
Labels: bug, non-breaking

#296 Switch to a self-hosted runner for publishing
  .github/workflows/wheels-publish.yaml
Labels: improvement, non-breaking

#297 Upload conda and wheel builds to Github Artifact Store
  .github/workflows/conda-cpp-build.yaml
  .github/workflows/conda-python-build.yaml
  .github/workflows/wheels-build.yaml
Labels: improvement, non-breaking

#299 Switched tree to ls in list-upload-directory
  .github/workflows/conda-cpp-build.yaml
  .github/workflows/conda-python-build.yaml
  .github/workflows/wheels-build.yaml
Labels: breaking, bug

#304 Report all files as changed temporarily
  .github/workflows/changed-files.yaml
Labels: bug, non-breaking

#306 chore: add cuda 11.4 to pull-request testing
  .github/workflows/conda-cpp-tests.yaml
  .github/workflows/conda-python-tests.yaml
Labels: improvement, non-breaking

#309 Use step-security/changed-files instead of tj-actions/changed-files
  .github/workflows/changed-files.yaml
Labels: bug, non-breaking

#312 Update `matrix_filter` handling
  .github/workflows/conda-cpp-build.yaml
  .github/workflows/conda-cpp-tests.yaml
  .github/workflows/conda-python-build.yaml
  .github/workflows/conda-python-tests.yaml
  .github/workflows/wheels-build.yaml
  .github/workflows/wheels-test.yaml
Labels: improvement, non-breaking

#314 Backport step-security/changed-files to 25.02
  .github/workflows/changed-files.yaml
Labels: bug, non-breaking

#308 make matrix type configurable
  .github/workflows/conda-cpp-build.yaml
  .github/workflows/conda-cpp-post-build-checks.yaml
  .github/workflows/conda-cpp-tests.yaml
  .github/workflows/conda-python-build.yaml
  .github/workflows/conda-python-tests.yaml
  .github/workflows/conda-upload-packages.yaml
  .github/workflows/custom-job.yaml
  .github/workflows/wheels-build.yaml
  .github/workflows/wheels-publish.yaml
  .github/workflows/wheels-test.yaml
Labels: improvement, non-breaking

#311 Add workflow to update `latest` and `default` branches
  .github/workflows/update-latest-branch.yaml
Labels: improvement, non-breaking

#321 Changed wheel_type to package_type
  .github/workflows/wheels-build.yaml
Labels: improvement, non-breaking

#323 Optional Input for CUDA suffix in wheel name
  .github/workflows/wheels-build.yaml
Labels: improvement, non-breaking
